name: gtk_header_bar
description: GtkHeaderBar for Flutter.
version: 0.0.1
homepage: https://github.com/jpnurmi/gtk_header_bar
repository: https://github.com/jpnurmi/gtk_header_bar
issue_tracker: https://github.com/jpnurmi/gtk_header_bar/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: GtkHeaderBarPlugin
